version: '3.1'

services:
    ubuntu-master:
      container_name: ubuntu-master
      restart: always
      privileged: true
      tty: true
      ports:
        - "52221:22"
        - "50070:50070"
      build:
        context: .

    ubuntu-slave1:
      container_name: ubuntu-slave1
      restart: always
      privileged: true
      tty: true
      ports:
        - "52222:22"
        - "50090:50090"
      build:
        context: .

    ubuntu-slave2:
      container_name: ubuntu-slave2
      restart: always
      privileged: true
      tty: true
      ports:
        - "52223:22"
      build:
        context: .